spring:
  application:
    name: csvParsingToDb

  datasource:
    url: jdbc:mysql://localhost:3306/csv?serverTimezone=UTC
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always
